### ISSUE TITLE
Always getting 24 results

### ISSUE THREAD

**Issue by aruizga7** [gippy/instagram-scraper#25]
I am trying to get the posts from this location: https://www.instagram.com/explore/locations/1947143972257299/la-mafia-se-sienta-a-la-mesa/ and I always get 24 results. When I try other locations...the same. Any recommended configuration?

**Comment by AndrewSB** [comment]
running into something like this too while getting posts from user URLs. Sometimes limited to 12, other times 24, seemingly randomly

**Comment by augustocamargo** [comment]
Same here, never more than 24 results.

**Comment by gippy** [comment]
I have just updated the code, there was one small mistake merged from the latest pull request.

**Comment by AndrewSB** [comment]
latest seems to work, thanks @gippy

**Comment by augustocamargo** [comment]
tks man!

**Comment by metalwarrior665** [comment]
The 24 results problem is still appearing. We are working on a fix asap.

**Comment by metalwarrior665** [comment]
Locations only allow 24 posts without login, with the login you can scroll normally. All other page types are working and scrolling well.
